/*
 * Generated by MTK Easy PinMux Tool Version 2.5.8 for 2822S. Copyright MediaTek Inc. (C) 2015.
 * 2020-05-14 14:18:33:0093
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
