/*
 * Generated by Airoha Easy PinMux Tool Version 2.6.2 for 2822S. Copyright Airoha Inc. (C) 2015.
 * 2020-02-28 16:00:04:0382
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
