/*
 * Generated by Airoha Easy PinMux Tool Version 2.7.2 for AB1568. Copyright Airoha Inc. (C) 2015.
 * 2021-08-12 16:16:08:0560
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
